#!/usr/bin/env bash

# Fuzzy find directories and outputs the selection

pkgs=`fd --min-depth 2 --max-depth 3 --type directory '' /workspace/$USER/ 2>/dev/null | grep src/`
fun=`fd --min-depth 1 --max-depth 2 --type directory '' ~/fun/ 2>/dev/null`
dev=`fd --min-depth 1 --max-depth 2 --type directory '' ~/dev/ 2>/dev/null`
home=`fd --min-depth 1 --max-depth 1 --type directory '' ~/`

printf "$pkgs\n$fun\n$dev\n$home" | sk

