#!/usr/bin/env bash

# Fuzzy find files and open the selection in neovim

files=`fd --type file \
    --exclude .git \
    --exclude mypy_cache \
    --exclude mypy_cache \
    --exclude __pycache__ \
    --exclude node_modules \
    --exclude *.bak \
    --exclude *.zip \
    --exclude dist \
    --exclude doc
`

selection=`printf "%s\n" "${files[@]}" | sk`

if [ -z "$selection" ]
then
    echo "File not chosen"
else
    nvim $selection
fi

